{{- range .Values.global.pulumiDeployment.additionalZone }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.kasmApp.name | default "kasm" }}-{{ .name }}-ingress
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Values.kasmApp.name }}-{{ .name }}-ingress
{{- include "kasm.defaultLabels" $ | indent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .loadBalancerIP }}
spec:
{{- if .Values.global.ingressClassName }}
  ingressClassName: {{ .Values.global.ingressClassName }}
{{- end }}
  tls:
  - hosts:
      - {{ $.Values.global.hostname | quote }}
      {{- if gt (len $.Values.global.altHostnames) 0 }}
        {{- range $.Values.global.altHostnames }}
      - {{ . | quote }}
      {{- end }}
      {{- end }}
    secretName: {{ $.Values.kasmCerts.ingress.name }}
  rules:
  - host: {{ .hostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kasm-{{ .name }}-proxy
            port:
              number: 8080
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: kasm-api
            port:
              number: 8080
{{- if $.Values.kasmApp.servicesToDeploy.kasmShare.deploy }}
      - path: /api/share/
        pathType: Prefix
        backend:
          service:
            name: kasm-share
            port:
              number: 8182
{{- end }}
{{- end }}

