apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: kasm-proxy-backend-config
  annotations:
    helm.sh/hook: pre-install,post-delete
spec:
  timeoutSec: 28800
  connectionDraining:
    drainingTimeoutSec: 60